In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
books = pd.read_csv('Books.csv')
users = pd.read_csv('Users.csv')
rating  = pd.read_csv('Ratings.csv')

<ipython-input-224-040734fcc48b>:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('Books.csv')


In [ ]:
print(books.columns)
print(books.shape)
books.head(2)

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')
(210180, 8)


ISBN           Book-Title           Book-Author Year-Of-Publication  \
0  0195153448  Classical Mythology    Mark P. O. Morford                2002   
1  0002005018         Clara Callan  Richard Bruce Wright                2001   

                 Publisher                                        Image-URL-S  \
0  Oxford University Press  http://images.amazon.com/images/P/0195153448.0...   
1    HarperFlamingo Canada  http://images.amazon.com/images/P/0002005018.0...   

                                         Image-URL-M  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   

                                         Image-URL-L  
0  http://images.amazon.com/images/P/0195153448.0...  
1  http://images.amazon.com/images/P/0002005018.0...

In [ ]:
del books['Image-URL-S']
del books['Image-URL-L']

In [ ]:
books.rename(columns={'Book-Title': 'title' , 'Book-Author':'author' , 'Year-Of-Publication':'year' ,'Publisher' :'publisher','Image-URL-M':'url'} , inplace = True)

In [ ]:
books.head(2)

ISBN                title                author  year  \
0  0195153448  Classical Mythology    Mark P. O. Morford  2002   
1  0002005018         Clara Callan  Richard Bruce Wright  2001   

                 publisher                                                url  
0  Oxford University Press  http://images.amazon.com/images/P/0195153448.0...  
1    HarperFlamingo Canada  http://images.amazon.com/images/P/0002005018.0...

In [ ]:
rating.head(2)

User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5

In [ ]:
rating.rename(columns={'User-ID':'user' , 'Book-Rating' : 'rating'},inplace = True)
rating.head(2)

user        ISBN  rating
0  276725  034545104X       0
1  276726  0155061224       5

In [ ]:
rating_name = rating.merge(books , on='ISBN')
rating_name.head(2)

In [ ]:
x = rating_name.groupby('user').count()['rating'] > 200
padhe_likhe_users = x[x].index

In [ ]:
rating_name = rating_name[rating_name['user'].isin(padhe_likhe_users)]

In [ ]:
rating_name.shape

(425122, 8)

In [ ]:
y = rating_name.groupby('title').count()['rating']>=50
famous_books = y[y].index

In [ ]:
final_rating = rating_name[rating_name['title'].isin(famous_books)]

In [ ]:
pt = final_rating.pivot_table(index='title',columns='user',values='rating')
pt.fillna(0,inplace=True)
pt

user                                                254     2276    2766    \
title                                                                        
1984                                                   9.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0    10.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
A Bend in the Road                                     0.0     0.0     7.0   
...                                                    ...     ...     ...   
Year of Wonders                                        0.0     0.0     0.0   
You Belong To Me                                       0.0     0.0     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0     0.0     0.0   
Zoya                                                   0.0     0.0     0.0   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   

user                                                2977    3363    4017    \
title                                                                        
1984                                                   0.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0     0.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
A Bend in the Road                                     0.0     0.0     0.0   
...                                                    ...     ...     ...   
Year of Wonders                                        7.0     0.0     0.0   
You Belong To Me                                       0.0     0.0     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0     0.0     0.0   
Zoya                                                   0.0     0.0     0.0   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   

user                                                4385    6251    6323    \
title                                                                        
1984                                                   0.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0     0.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
A Bend in the Road                                     0.0     0.0     0.0   
...                                                    ...     ...     ...   
Year of Wonders                                        0.0     0.0     0.0   
You Belong To Me                                       0.0     0.0     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0     0.0     0.0   
Zoya                                                   0.0     0.0     0.0   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   

user                                                6543    ...  271448  \
title                                                       ...           
1984                                                   0.0  ...     0.0   
1st to Die: A Novel                                    9.0  ...     0.0   
2nd Chance                                             0.0  ...     0.0   
4 Blondes                                              0.0  ...     0.0   
A Bend in the Road                                     0.0  ...     0.0   
...                                                    ...  ...     ...   
Year of Wonders                                        0.0  ...     0.0   
You Belong To Me                                       0.0  ...     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0  ...     0.0   
Zoya                                                   0.0  ...     0.0   
\O\" Is for Outlaw"                                    

In [ ]:
np.where(pt.index == 'Harry Potter and the Chamber of Secrets (Book 2)')[0][0]

215

In [ ]:
np.where(pt.index == '1984')

(array([0]),)

In [ ]:
from scipy.sparse import csr_matrix
book_sparse = csr_matrix(pt)

In [ ]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(algorithm='brute')
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [ ]:
distances , suggestions = model.kneighbors(pt.iloc[230].values.reshape(1,-1), n_neighbors=6)

In [ ]:
distances

array([[ 0.        , 27.73986301, 30.51638904, 30.61453903, 30.88689042,
        31.37275888]])

In [ ]:
suggestions

array([[230, 147, 612, 652, 420, 165]])

In [ ]:
for i in range(len(suggestions[0])):
  print(pt.index[suggestions[0][i]] , end='\n')

Hideaway
Dragon Tears
Tom Clancy's Op-Center (Tom Clancy's Op Center (Paperback))
Winter Moon
Sole Survivor
Exclusive


In [ ]:
 print(pt.index[suggestions[0][1]])

Dragon Tears


In [ ]:
def searchBook(book):
  bookId = np.where(pt.index == book)[0][0]
  distances , suggestions = model.kneighbors(pt.iloc[bookId].values.reshape(1,-1), n_neighbors=6)
  books = []
  for i in range(len(suggestions[0])):
    if i != 0:
      # print(pt.index[suggestions[0][i]])
      books.append(pt.index[suggestions[0][i]])
  return books

In [ ]:
recbooks = searchBook('Harry Potter and the Prisoner of Azkaban (Book 3)')

Harry Potter and the Goblet of Fire (Book 4)
Harry Potter and the Chamber of Secrets (Book 2)
Harry Potter and the Order of the Phoenix (Book 5)
Harry Potter and the Sorcerer's Stone (Book 1)
Exclusive


In [ ]:
recbooks

['Harry Potter and the Goblet of Fire (Book 4)',
 'Harry Potter and the Chamber of Secrets (Book 2)',
 'Harry Potter and the Order of the Phoenix (Book 5)',
 "Harry Potter and the Sorcerer's Stone (Book 1)",
 'Exclusive']

In [ ]:
books.drop_duplicates('title')

In [ ]:
import pickle
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(books,open('books.pkl','wb'))
pickle.dump(model,open('model.pkl','wb'))

In [ ]:
def recommend(book):
  book = searchBook(book)
  tempdf = books[books['title'].isin(book)]
  return tempdf

In [ ]:
test = recommend('Harry Potter and the Prisoner of Azkaban (Book 3)')

In [ ]:
cc = test.drop_duplicates('title')

In [ ]:
cc.iloc[1].title

'Harry Potter and the Chamber of Secrets (Book 2)'